setup.sh
=> Adding missing shebang

docs/install.md, setup.sh
=> Check that rustup and pip3 are installed

docs/install.md
As requested in #27, I added a line to the documentation about test websites you can try to verify that your key is working.
=> Mentions webauthn.io at the end of install.md.

docs/install.md
Merge patch-2 into patch-1.
Apparently I cannot commit to the `gendx-patch-1` branch (created in the web UI) because it is [protected](https://help.github.com/en/github/administering-a-repository/about-protected-branches), so need to create a recursive pull request for that.
=> Fix review comments for #39

.vscode/extensions.json, .vscode/settings.json, deploy.py
- Check that JLinkExe is properly installed
- Verify that the app is installed
- Always report failures in the exit code
- Add vscode settings for Python code formatting using Google style
- Fix issue #42 regarding tockloader version and sticky parameter
Fixes #42
=> Improve deploy script.

docs/install.md
=> Document troubleshooting on OS X

deploy.py
=> Fix errors in deploy script.

patches/tock/04-fix-dynamic-deferred-call.patch
This imports the patch for https://github.com/google/OpenSK/issues/58 until the bug is fixed upstream and we can update the git submodule.
=> Import bugfix from https://github.com/tock/tock/pull/1636 as a patch.

deploy.py
Ensure that the version of Nordic's `nrfutil` tool is one we can work with.
=> Check nrfutil version.

docs/install.md
This pull request adds more details to the installation instructions regarding which packages should be installed on Debian.
=> More detailed installation instructions.

deploy.py
=> Fix parsing logic of deploy.py script

src/ctap/mod.rs
Desktop tests passed.
test suite passed.
=> Removed duplicated code in process_get_assertion

src/ctap/mod.rs
Solves issue #188.
- Passed desktop tests.
- Passed test tool.
=> Always set default credential policy

libraries/persistent_store/src/format.rs, libraries/persistent_store/src/lib.rs, libraries/persistent_store/src/model.rs, libraries/persistent_store/src/store.rs
Tests need the driver which will be the next PR.
=> Add new store (without tests yet)

src/ctap/storage.rs
Fixes #201 
Does what the title says, we only change a constant here.
=> Change maximum PIN retries to 8

src/ctap/mod.rs
The test tool now checks for this version string and adapts accordingly. It shouldn't hurt that we are not feature complete yet, since it is only the `PRE` version.
=> adds FIDO 2.1 PRE version string

libraries/persistent_store/src/driver.rs, libraries/persistent_store/src/lib.rs, libraries/persistent_store/src/store.rs
This also adds the store tests.
=> Add driver for new store

.github/workflows/cargo_fuzz.yml, libraries/persistent_store/fuzz/.gitignore, libraries/persistent_store/fuzz/Cargo.toml, libraries/persistent_store/fuzz/fuzz_targets/store.rs, libraries/persistent_store/fuzz/src/lib.rs, run_desktop_tests.sh
I can't add @mingxguo27 as reviewer, so pinging here in the description.
If you want to see the final fuzzing code to understand how things are used, you can look at https://github.com/ia0/OpenSK/tree/v2/libraries/persistent_store/fuzz.
=> Create fuzzing and add entropy helpers

libraries/persistent_store/fuzz/src/histogram.rs, libraries/persistent_store/fuzz/src/lib.rs
cc @mingxguo27 (same issue as before, can't add to reviewer)
As before, full code for context is here: https://github.com/ia0/OpenSK/tree/v2/libraries/persistent_store/fuzz.
=> Add histogram for fuzzing

libraries/persistent_store/fuzz/Cargo.toml, libraries/persistent_store/fuzz/src/histogram.rs, libraries/persistent_store/fuzz/src/lib.rs, libraries/persistent_store/fuzz/src/stats.rs
=> Add stats for fuzzing

src/ctap/mod.rs
Implements the [specification clarification](https://github.com/fido-alliance/fido-2-specs/pull/933).
=> Tries to unwrap credentials in the exclude list

src/ctap/ctap1.rs, src/ctap/mod.rs
Blocks #196. Allows the `rk=false` option together with the HMAC-secret extension.
=> Allow HMAC secret with rk=false

libraries/persistent_store/src/driver.rs
We prefer to return those errors to the fuzzer which can then decide whether they are expected or not (e.g. when starting from a dirty storage, the store is expected to have errors).
=> Do not crash in the driver for store errors

libraries/persistent_store/fuzz/Cargo.toml, libraries/persistent_store/fuzz/fuzz_targets/store.rs, libraries/persistent_store/fuzz/src/lib.rs, libraries/persistent_store/fuzz/src/store.rs
=> Add store fuzzing

libraries/persistent_store/fuzz/examples/store.rs
This permits to debug a single artifact or get statistics about a corpus.
=> Add debug helper for fuzzing

src/ctap/apdu.rs, src/ctap/mod.rs
The target of this PR is to have a separate module for parsing APDUs.
Supported APDUs:
---
=> Add APDUs Parser

libraries/persistent_store/fuzz/src/store.rs, libraries/persistent_store/src/driver.rs
This permits to avoid copies. Before we used to do one copy per storage operation. Now we do one copy per store operation.
=> Do not use delay_map anymore

src/ctap/hid/mod.rs
Fixes #241 
To facilitate discussion, this is the PR that would fix #241, if we want to.
=> changes channel ID endianness to big endian
