google/OpenSK

libraries/crypto/Cargo.toml
The `Cargo.toml` at the root directory already uses version 0.3.6, let's update the one in the crypto library as well.
=> Update arrayref version in libraries/crypto.

libraries/crypto/src/ec/point.rs, libraries/crypto/src/ecdh.rs, libraries/crypto/src/ecdsa.rs
Some tests take more than 60 seconds to run on Travis. This PR disables some tests or decreases the number of iterations when debug assertions are enabled, according to the tests taking more than 60 seconds on this build: https://travis-ci.org/google/OpenSK/builds/646810262.
=> Decrease the number of tests in debug mode, to account for slower CI on Travis

.travis.yml, run_desktop_tests.sh
Try to catch bugs earlier on Mac OS X by also running travis-ci on this os.
In order to speed up the builds, unit testing is only enabled on Linux or outside of Travis.
=> Enable Travis on OSX

deploy.sh
This change forwards enabled features to the crypto bench example, like it's done for the CTAP app. This allows to deploy things like `./deploy.sh --panic-console crypto_bench` and indeed have the panic message being printed to the console.
=> Pass features to crypto bench example.

run_desktop_tests.sh
The script begins with `set -eux` and therefore will fail when using an
undefined variable. This is the case with `TRAVIS_OS_NAME` outside of
Travis.
=> Fix run_desktop_tests.sh script

src/ctap/ctap1.rs, src/ctap/key_material.rs, src/ctap/mod.rs
Some of the slices obtained with `include_bytes` were dereferenced to be stored in arrays, and were then referenced again upon use. This change removes these back and forth conversions.
=> Don't dereference slices obtained from include_bytes.

libraries/crypto/Cargo.toml, libraries/crypto/src/ecdsa.rs
This updates the `ring` dependency to the latest available version. This also allows to check if the `cargo audit` warning is resolved by that.
=> Update the ring dev dependency version.

setup.sh
The reset script was apparently not documented. A user had to re-clone the project to restore a valid state: https://github.com/google/OpenSK/issues/25#issuecomment-583917950.
=> Add instructions to re-run setup.sh

patches/libtock-rs/06-no_spin_allocator.patch
This change uses the heap of `linked_list_allocator` directly instead of locking it via a mutex. Since the app is single threaded this shouldn't be a problem.
This also allows to remove the `spin` dependency of `linked_list_allocator`, which isn't maintained anymore since RUSTSEC-2019-0031, thereby addressing one half of #24.
After this change, `cargo audit` should only mention `spin` via the `ring` dev-dependency.
=> Don't lock the allocator with spin.

docs/install.md
`ioreg -P USB` doesn't work, it should be `ioreg -p USB` to get usb list in Mac OS X.
=> Fixed incorrect command in install.md.

build.rs
Because of libtock-rs we can't run clippy on our codebase. But it could
run at least on `build.rs`.
=> Fix clippy warnings.

.github/workflows/cargo_audit.yml
The env context is only available at the step level, not the job one so
we need to use the github context instead. But the head_ref will only be
populated if we run in a pull_request event. So until we find a better
solution, let's match on the repo URL.
=> Fix cargo audit workflow

.pylintrc, deploy.py
It seems that our internal linter is stricter than what pylint does.
Fixing the python code to make both happy and tries to fix the gap by
modifying pylintrc configuration file
=> Make internal python linter happy.

.github/workflows/cargo_check.yml, Cargo.toml, deploy.py, patches/libtock-rs/07-debug_allocations.patch, run_desktop_tests.sh
This PR adds a `--debug-allocations` parameter to the `deploy.py` script. This parameter enables a Cargo feature to add tracking of allocations in libtock-rs, and printing general statistics (total memory usage, number of allocated pointers) to the console.
=> Add feature to track allocations in libtock-rs

patches/tock/05-usb-cancel.patch
Fixes #71.
Although CTAP HID uses a bidirectional USB endpoint, there was currently only one state per endpoint. However, in order to accept cancellation packets we need to split the endpoint state into 2 independent directions.
This additional patch fixes that by splitting the endpoint state into an IN state and an OUT state, each having its own buffer. This fixes the observed issue.
I'll also send a pull-request upstream for the changes in the chip and HIL, together with the relevant changes in `patches/tock/02-usb.patch`.
=> Add patch for bidirectional USB endpoints to fix panics in case of cancellation.

.github/workflows/opensk_build.yml, boards/nrf52840_mdk_dfu/src/main.rs, run_desktop_tests.sh
To move towards reproducible builds (#70), this pull-request syncs the kernel with upstream now that https://github.com/tock/tock/pull/1668 and https://github.com/tock/tock/pull/1669 have been merged. The `sha256sum` tool is also used to compute the sum of the built binary on CI.
=> Sync upstream kernel to get more reproducible builds.

src/ctap/data_formats.rs, src/ctap/mod.rs, src/ctap/storage.rs
Fixes #74 
This is the extension implementation for HMAC-secret. This is required for Windows Hello passwordless logins.
This is still WIP, the extension has not been tested on Windows 10 yet.
=> adding HMAC-secret support

.github/workflows/cargo_check.yml, Cargo.toml, deploy.py, run_desktop_tests.sh, src/usb_ctap_hid.rs
This pull request adds a `--verbose` parameter to print all USB packets sent or received by the OpenSK app. The "Cancelling USB due to timeout" messages are also now gated by this `--verbose` flag, as they otherwise add quite some noise.
=> Add a --verbose parameter to print all USB packets at the OpenSK level.

.github/workflows/python.yml, deploy.py, setup.sh
Fixes #79 
tockloader 1.4.0 has been released and pushed to pypi.
Now we require at least tockloader 1.4.x for our `deploy.py` script.
Github workflows have been updated too.
=> Depends on tockloader 1.4.x from now

deploy.py
This pull request adds a `--verbose-build` option to the deploy script, to print detailed output about the various building steps.
=> Add a --verbose-build option to the deploy script.

deploy.py
Tockloader 1.4 added the parameter to bundle apps and bails out if this parameter doesn't exists.
=> Add missing parameter that got introduced in tockloader 1.4

.github/workflows/cargo_check.yml, .github/workflows/opensk_test.yml, Cargo.toml, README.md, deploy.py, run_desktop_tests.sh, src/ctap/command.rs, src/ctap/data_formats.rs, src/ctap/mod.rs, src/ctap/response.rs
This is the start of a series of pull requests for 2.1 features. First command: GetInfo.
Also, the data type PublicKeyCredentialParameter is now used in 2 places and is refactored into a new struct.
Changes should all be backwards compatible. We only add more optional commands and outputs.
=> add 2.1 features to GetInfo

.github/workflows/reproducible.yml, .gitignore, deploy.py, reproduce_board.sh, reproduce_hashes.sh, reproducible/reference_elf2tab.txt, reproducible/reference_elf2tab_macos-10.15.txt, reproducible/reference_elf2tab_ubuntu-18.04.txt
This pull request adds a dump of elf2tab to the reproducible workflow. This allows to easily check for regressions in binary size, notably thanks to the following lines.
```
Number of writeable flash regions: 0
Adding .crt0_header section. Offset: 64 (0x40). Length: 64 (0x40) bytes.
Entry point is in .text section
Adding .text section. Offset: 128 (0x80). Length: 176436 (0x2b134) bytes.
Adding .stack section. Offset: 176564 (0x2b1b4). Length: 16384 (0x4000) bytes.
```
=> Add elf2tab output to the reproducible checks

.github/workflows/reproducible.yml
This change allows to see both the binary size comparison and the hashes comparison, even if the former failed. Otherwise, the job would be cancelled after the first failure, preventing us from seeing all the diffs.
Note: It's unclear from the documentation how GitHub will aggregate the status of the whole job in case one step fails but not the next. We might have to adjust that after seeing the effect in practice on pull requests. On the other hand, if the sizes don't match, the cryptographic hashes shouldn't match either.
=> Always run git-diff in reproducible workflow, even if the job failed so far.

reproduce_hashes.sh
This adds the `reproducible/elf2tab.txt` and `reproducible/binaries.sha256sum` files to the `reproduced.tar` archive that is uploaded in the "check reproducible" GitHub action, to make it easier to update the reference binaries in pull requests.
=> Add reference elf2tab and binary hashes to the uploaded reproduced.tar file

.github/workflows/python.yml, deploy.py, setup.sh
Fixes #130 
Just moving to a newer version of tockloader.
We don't need anymore to craft a fake app for padding as tockloader 1.5 understand what padding is and provides a dedicated object.
=> Move to tockloader 1.5

deploy.py, examples/console_test.rs, third_party/libtock-drivers/src/console.rs
This example is inspired by https://github.com/gendx/libtock-rs/commit/9a25591ccdfa51c99a6b641a11bcc9eeb32967da and the discussion at https://github.com/tock/tock/issues/1697. It can be used to make sure that the buffering performed by the `Console` driver is handled properly by TockOS.
=> Add console_test example to stress-test Tock's console driver.

.gitignore, deploy.py, reset.sh, setup.sh
Since #145, `elf2tab` is installed in the OpenSK root directory.
- This is not clean as the `.crates.toml` and `.crates2.json` files appear in the root.
- The `reset.sh` script removes this local `elf2tab` installation, which means that a full compilation of `elf2tab` will happen again on the next `./setup.sh` run. This is not necessary, as the setup script will check the version and re-install it if a version upgrade is needed.
This pull request installs `elf2tab` in its own sub-directory instead, which is excluded from the `reset.sh` script.
=> Install elf2tab in its own directory.

libraries/persistent_store/src/format.rs, libraries/persistent_store/src/format/bitfield.rs, libraries/persistent_store/src/lib.rs, libraries/persistent_store/src/model.rs, libraries/persistent_store/src/storage.rs, libraries/persistent_store/src/store.rs
This PR does the following things:
- Give incompatible representations for integers with different semantics (this hopefully further clarifies comments from previous PRs: [`usize` vs `u32`](https://github.com/google/OpenSK/pull/166#discussion_r496904845) and [`Position`](https://github.com/google/OpenSK/pull/172#discussion_r500997209)):
- `usize` is used for natural numbers for the public API.
- `Nat` is used internally for natural numbers (essentially a stable `usize`).
- `Word` is used for sequences of bits representing words in flash.
- `Position` is used for word positions in the virtual storage.
- Only use fixed size integers to preserve overflow behavior between targets (this improves fuzzing coverage).
- Use little-endian representation instead of native representation for `Word` …
=> Clarify different integer types

src/ctap/hid/mod.rs
Cont packets were not silently ignored so far, if their CID was outside the allocated range.
Blocks #196
=> Change priority of errors for HID

.github/workflows/crypto_test.yml
The use of `::set-env` command in workflows is not being depreacted.
Moving to the new way of setting environment variables.
Fixes #214
> It's a good idea to open an issue first for discussion.
=> Fix broken crypto_test workflow.

src/ctap/hid/mod.rs, src/ctap/hid/receive.rs
Resolves an old TODO in HID to correctly respond to syncs.
=> Change response in HID_INIT for sync

src/ctap/data_formats.rs
Blocks #196 . While still being discussed in the specification, we probably want the behaviour that works with certification. We can always revert back if it turns out to work with the old implementation.
=> fail on UP=true in make

src/ctap/pin_protocol_v1.rs
Blocks #196.
We had a subtle bug where this line was 1 line above its correct position:
> let output1 = hmac_256::<Sha256>(&cred_random_secret, &decrypted_salt1[..]);
There was a gap in testing, that should be fixed now.
=> makes HMAC secret output reproducible

src/ctap/mod.rs
The spec introduced a feature where empty PIN auth parameters are used to trigger user presence checks. This is already checked in the test tool, and now also reflected here.
#106
=> Adds a UP check for device identification

src/ctap/ctap1.rs, src/ctap/key_material.rs, src/ctap/mod.rs, src/ctap/storage.rs
Part of the changes needed for #195 
This also prepares removing the crypto material from the firmware by:
* defining `attestation_private_key` as sensitive in the storage
* ensuring that the certificate and the private key are one-time programmable
=> Ensure CTAP1 uses the storage to access attestation material

fuzz/fuzz_helper/src/lib.rs, src/ctap/command.rs, src/ctap/ctap1.rs, src/ctap/data_formats.rs, src/ctap/hid/mod.rs, src/ctap/mod.rs, src/ctap/storage.rs, src/main.rs
Fixes #196.
This PR implements the GetNextAssertion. This includes saving the command state in GetAssertion, and discarding it on timeout or intersecting commands. The correct behaviour for timeouts landed in CTAP 2.1, and should be backwards compatible to 2.0.
Added @jmichelp for the CTAP changes and double-checking with the conformance tool.
Added @ia0 for reviewing the storage changes.
=> GetNextAssertion

src/ctap/data_formats.rs, src/ctap/mod.rs, src/ctap/pin_protocol_v1.rs, src/ctap/storage.rs
Blocks #196 . And hopefully fixes it this time.
Returning user data is mandatory, so we added it to the store. We deviate from `WebAuthn`'s `CredentialSource` now, so I renamed `OtherUi` to what we actually used it for, the `DisplayName` in user. This should still be backwards compatible with the store, just adding @ia0 for checking.
=> Adds user data to stored credentials

libraries/persistent_store/fuzz/src/store.rs, libraries/persistent_store/src/buffer.rs, libraries/persistent_store/src/store.rs
Also rename `strict_write` to `strict_mode` to enhance that it enables additional checks.
The dirty init already used to set `strict_write` to false.
=> Do not crash with dirty init

src/ctap/apdu.rs
It seems we missed that during the initial code review.
=> Add missing license header.

src/ctap/ctap1.rs, src/ctap/data_formats.rs, src/ctap/mod.rs, src/ctap/pin_protocol_v1.rs, src/ctap/storage.rs
This PR implements the new version of the HMAC-secret extension. It does so by reverting the extension of key handles in #218, now implicitly creating `cred_random` values deterministically from the credential and 2 new device secrets.
Part of #106 , but backwards compatible to the 2.0 version.
@jmichelp for checking the idea
@ia0 for storage
optional FYI @gendx for crypto (i.e. `generate_cred_random`)
=> implicitly generate HMAC-secret

third_party/lang-items/Cargo.toml
`linked-list-allocator` released version 0.8.7 today which adds a feature that we need to preserve previous behavior. See https://github.com/phil-opp/linked-list-allocator/blob/master/Changelog.md#087--2020-12-10
=> Fix lang items

src/ctap/command.rs
Continuing on #106. Some command codes were incorrect, this reflects the state of review draft. Some command codes are conceptual only (i.e. `AUTHENTICATOR_VENDOR_FIRST_UNUSED`), they are commented out to eventually be able to drop `#[allow(dead_code)]`.
=> updates command bytes

src/ctap/hid/mod.rs, src/ctap/mod.rs, src/ctap/pin_protocol_v1.rs, src/ctap/status_code.rs, src/ctap/storage.rs
Continues #106 . Updates status codes, unifies existing vendor specific error codes. Same style as #244 .
=> Updates status codes for RD02 of CTAP 2.1
